### ISSUE TITLE
ATECC608A support

### ISSUE THREAD

**Issue by DurandA** [mongoose-os-libs/atca#1]
I want to use the newer ATECC608A to perform HKDF and AES. Which version of CryptoAuthLib is included with the latest Mongoose OS?

The ATECC608A almost fully compatible with the ATECC508A. According to my experience, some newer function are only enabled if the `ATCAIfaceCfg` is initialized with an ATECC608A devtype:
```
ATCAIfaceCfg cfg = cfg_ateccx08a_i2c_default;
cfg.devtype = ATECC608A;
```

What are the options to use functions like `atcab_kdf` and `atcab_aes_cbc_*` from Mongoose OS?

**Comment by rojer** [comment]
cryptoauthlib used is 20160108 + some fixes, the source is [here](https://github.com/cesanta/mongoose-os/tree/18b70d1ffe65e65c7788de3c1b4e7b7f8c634f91/third_party/cryptoauthlib).

we haven't looked into 608 support yet. i can say upfront that using symmetric ciphers is probably not a good idea - all the platforms in question can do AES fast enough for it not to be an issue, and you will be sending plain text data over the bus which can be easily tapped.

**Comment by DurandA** [comment]
Does your patched *Mbed TLS* use hardware acceleration for AES when used with ESP32?

**Comment by rojer** [comment]
yes. hardware AES and MPI modexp and modmul are used.

**Comment by DurandA** [comment]
I want to update the built-in cryptoauthlib. How should I proceed since it [has been removed](https://github.com/cesanta/mongoose-os/commit/6554e5bbb459c86d7aec7e891e4490a48c27e585) from the main repo?

**Comment by rojer** [comment]
yeah, it was removed as part of cleaning out the repo. i'm afraid there's no good answer to that, as both the lib and the closed-source mbedtls are built in our private repo. you can file a request to update cryptoauthlib and either wait until we get around to it or talk to @cpq to buy some of our time to do it.

**Comment by DurandA** [comment]
Thank you for the quick and clear answer.
