### ISSUE TITLE
ATCA:0 In configuration file

### ISSUE THREAD

**Issue by Enophi** [mongoose-os-libs/atca#5]
Hello,

After provisionned a barebone ATEC608A, i have this log :
```
mgos_vfs.c:280          ATCA:0 -> /ATCA:0 pl 1 -> 1 0x3ffefe4c (refs 1)
mgos_vfs.c:375          open ATCA:0 0x0 0x1b6 => 0x3ffefe4c ATCA:0 -1 => -1 (refs 0)
```
It seems that the configuration using the ATEC:0 syntax try load from vfs. In my case it's the mqtt.ssl_key use by the mqtt lib.

I really dont know how to solve by myself this error.

Thanks in advance for your time.

**Comment by rojer** [comment]
it looks like you're using mbedtls without ATCA support. enable it by setting the variable - `MGOS_MBEDTLS_ENABLE_ATCA` build)var - https://github.com/mongoose-os-libs/mbedtls/blob/master/mos.yml#L42

add this to your app manifest (it will override the default):

```
build_vars:
  MGOS_MBEDTLS_ENABLE_ATCA: 1
```

**Comment by Enophi** [comment]
It works like a charm. Thank you very much!
